-- V2__create_drivers_table.sql


CREATE TABLE IF NOT EXISTS drivers (
                                       id UUID PRIMARY KEY,                         -- UUID generated by app (@GeneratedValue)
                                       name VARCHAR(255) NOT NULL,
    current_location geometry(Point,4326),       -- JTS <-> PostGIS geometry
    on_shift BOOLEAN NOT NULL DEFAULT FALSE
    );


CREATE UNIQUE INDEX IF NOT EXISTS uq_drivers_name ON drivers (name);

-- Spatial index for KNN queries with <-> operator
CREATE INDEX IF NOT EXISTS idx_drivers_current_location_gix
    ON drivers
    USING GIST (current_location);

