-- V2__create_drivers_table.sql
-- JTS-compatible: store as geometry(Point,4326)

CREATE TABLE IF NOT EXISTS drivers (
                                       id UUID PRIMARY KEY,                         -- UUID generated by app (@GeneratedValue)
                                       name VARCHAR(255) NOT NULL,
    current_location geometry(Point,4326),       -- JTS <-> PostGIS geometry
    on_shift BOOLEAN NOT NULL DEFAULT FALSE
    );

-- Uniqueness on driver name (case-sensitive). If you want case-insensitive uniqueness,
-- use: CREATE UNIQUE INDEX uq_drivers_name_ci ON drivers ((lower(name)));
CREATE UNIQUE INDEX IF NOT EXISTS uq_drivers_name ON drivers (name);

-- Spatial index for KNN queries with <-> operator
CREATE INDEX IF NOT EXISTS idx_drivers_current_location_gix
    ON drivers
    USING GIST (current_location);

-- ─────────────────────────────────────────────────────────────────────────────
-- Seed data (WGS84; coordinates are (lon, lat))
-- ─────────────────────────────────────────────────────────────────────────────

-- Alice - Denver, CO (on shift)
INSERT INTO drivers (id, name, current_location, on_shift) VALUES
    ('e7cd6b10-0339-4a38-8a6d-2216f8004b23', 'alice',
     ST_SetSRID(ST_MakePoint(-104.9903, 39.7392), 4326)::geometry, TRUE);

-- Bob - Boulder, CO (on shift)
INSERT INTO drivers (id, name, current_location, on_shift) VALUES
    ('8de39071-597b-4802-871f-78b2a6aded34', 'bob',
     ST_SetSRID(ST_MakePoint(-105.27055, 40.01499), 4326)::geometry, TRUE);

-- Carol - Phoenix, AZ (off shift)
INSERT INTO drivers (id, name, current_location, on_shift) VALUES
    ('dde7f793-22f5-4423-912f-80bc99e1bd9a', 'carol',
     ST_SetSRID(ST_MakePoint(-112.0740, 33.4484), 4326)::geometry, FALSE);
